project_name: parampiper

before:
  hooks:
    - go mod tidy

builds:
  - binary: parampiper
    id: pp-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -w -s -X github.com/cdalar/parampiper/cmd.Version=v{{.Version}}-{{.ShortCommit}} 
      - -X github.com/cdalar/parampiper/cmd.BuildTime={{.Date}}
    
  - binary: parampiper
    id: pp
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64 # M1
    ldflags:
      - -w -s -X github.com/cdalar/parampiper/cmd.Version=v{{.Version}}-{{.ShortCommit}}
      - -X github.com/cdalar/parampiper/cmd.BuildTime={{.Date}}
      # - -X github.com/cdalar/parampiper/cmd.GoVersion=$(go version)
    # hooks:
      # post: ["gon gon/config-{{.Arch}}.json"]


archives:
  - id: repl
    name_template: "{{ .ProjectName }}_{{.Os}}_{{.Arch}}_{{.Version}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    # files:
    #   - non-existent*

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: cdalar
    name: parampiper
  prerelease: auto

brews:
  - repository:
      owner: cdalar
      name: homebrew-tap
    description: "parampiper"
